"""Closed vocabularies must stay closed in the documentation too.

`ReasonCode` and the capability vocabulary are published contracts: a reader greps the docs for a
code, and a code that exists in the enum but not in the docs is undocumented, while one that exists
in the docs but not in the enum is a promise the code cannot keep. Both defects have happened here,
which is why they are asserted rather than reviewed.

The reason-code listing was previously regenerated by hand and drifted within a single release. It is
now compared, in both languages, against the enum itself.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

import pytest

from vidliner.capabilities.names import KNOWN_CAPABILITIES
from vidliner.domain.reasons import ReasonCode

REPO_ROOT = Path(__file__).resolve().parents[2]

#: Documentation files that list every reason code, with the header that introduces the listing.
REASON_CODE_DOCS = (
    "docs/design/quality-metrics.md",
    "docs/zh/design/quality-metrics.md",
    "docs/quality.md",
    "docs/zh/quality.md",
)

#: Documentation files that must name every capability in the vocabulary.
CAPABILITY_DOCS = ("docs/backends.md", "docs/zh/backends.md")

#: Documentation files that cite test functions by name.
TEST_NAME_DOCS = (
    "docs/testing.md",
    "docs/zh/testing.md",
    "docs/design/milestones.md",
    "docs/zh/design/milestones.md",
)

_CODE = re.compile(r"\b([A-Z][A-Z0-9_]{3,})\b")

#: A cited test function, optionally with a module extension (``test_export.py`` is a path, not a
#: function) and optionally a trailing ``_`` (``test_operators_*.py`` is a glob).
_CITED_TEST = re.compile(r"\btest_[a-z0-9_]+(\.[a-z]+)?")


def _listing(path: str) -> list[str]:
    """The reason codes listed in ``path``, in the order the file lists them."""
    text = (REPO_ROOT / path).read_text(encoding="utf-8")
    header = "## Reason codes" if "## Reason codes" in text else "## Reason code"
    start = text.index(header)
    open_fence = text.index("```", start)
    close_fence = text.index("```", open_fence + 3)
    return _CODE.findall(text[open_fence + 3 : close_fence])


@pytest.mark.parametrize("path", REASON_CODE_DOCS)
def test_every_reason_code_is_listed_exactly_once(path: str) -> None:
    listed = _listing(path)
    expected = [code.name for code in ReasonCode]
    assert listed == expected, (
        f"{path} does not list the reason codes in enum order; "
        f"missing={set(expected) - set(listed)}, extra={set(listed) - set(expected)}"
    )


@pytest.mark.parametrize("path", CAPABILITY_DOCS)
def test_every_capability_is_documented(path: str) -> None:
    text = (REPO_ROOT / path).read_text(encoding="utf-8")
    undocumented = [capability for capability in KNOWN_CAPABILITIES if capability not in text]
    assert not undocumented, f"{path} does not document: {undocumented}"


@pytest.mark.parametrize("path", CAPABILITY_DOCS)
def test_the_capability_count_matches_the_vocabulary(path: str) -> None:
    """A capability added to the vocabulary must be added to the table, not just mentioned."""
    text = (REPO_ROOT / path).read_text(encoding="utf-8")
    rows = [line for line in text.splitlines() if line.startswith("| `")]
    documented = {capability for capability in KNOWN_CAPABILITIES if any(capability in row for row in rows)}
    assert documented == set(KNOWN_CAPABILITIES), (
        f"{path} has no table row for: {sorted(set(KNOWN_CAPABILITIES) - documented)}"
    )


def _defined_tests() -> set[str]:
    """Every test function name defined anywhere under ``tests/``."""
    names: set[str] = set()
    for path in (REPO_ROOT / "tests").rglob("*.py"):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                names.add(node.name)
    return names


def _cited_tests(text: str) -> set[str]:
    """Test functions a document refers to by name, ignoring module paths and globs."""
    cited: set[str] = set()
    for match in _CITED_TEST.finditer(text):
        if match.group(1) or match.group(0).endswith("_"):
            continue
        cited.add(match.group(0))
    return cited


@pytest.mark.parametrize("path", TEST_NAME_DOCS)
def test_every_cited_test_exists(path: str) -> None:
    """A document that names a test must name one that exists.

    The verification record is the project's evidence that a requirement is met. A row pointing at a
    renamed test is worse than no row: it reads as proof and is not.
    """
    defined = _defined_tests()
    cited = _cited_tests((REPO_ROOT / path).read_text(encoding="utf-8"))
    missing = sorted(name for name in cited if name not in defined)
    assert not missing, f"{path} cites tests that do not exist: {missing}"


def test_the_citation_extractor_ignores_module_paths() -> None:
    """Otherwise the check would pass by extracting nothing, or fail on every ``.py`` mention."""
    assert _cited_tests("see `test_export_roundtrips`") == {"test_export_roundtrips"}
    assert _cited_tests("pytest tests/pipeline/test_export.py") == set()
    assert _cited_tests("pytest tests/unit/test_operators_*.py") == set()
